application: interedition-tools
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /v-machine
  static_dir: v-machine

- url: /frames
  static_dir: frames

- url: /plaintext_tokenize
  script: plaintext_tokenize.py

- url: /return_texts
  script: find_texts.py

- url: /run_toolchain
  script: dispatcher.py

- url: /teidisplay
  script: teiResult.py

- url: /htmldisplay
  script: htmlResult.py

- url: /graphmldisplay
  script: graphmlResult.py

- url: /test.*
  login: admin
  script: gaeunit.py

- url: /.*
  script: index.py
